/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package it.unibas.iqmeter.view.wizard;

import it.unibas.iqmeter.Constant;
import it.unibas.iqmeter.Utils;
import it.unibas.iqmeter.controller.ActionChooseFile;
import it.unibas.iqmeter.controller.ActionSelectTool;
import it.unibas.iqmeter.controller.wizard.ActionBackStep4;
import it.unibas.iqmeter.controller.wizard.ActionFinishStep4;
import it.unibas.iqmeter.model.MappingTool;
import it.unibas.iqmeter.view.presentationmodel.MappingToolPM;
import it.unibas.ping.binding.Form;
import it.unibas.ping.binding.IForm;
import it.unibas.ping.binding.collegatori.CollegatoreComboBox;
import it.unibas.ping.binding.collegatori.CollegatoreTextField;
import it.unibas.ping.binding.collegatori.ICollegatore;
import it.unibas.ping.binding.osservatori.IOsservatore;
import it.unibas.ping.binding.osservatori.OsservatoreTextField;
import it.unibas.ping.convalida.ConvalidatoreValoreAstratto;
import it.unibas.ping.convalida.IConvalidatoreValore;
import it.unibas.ping.framework.FinestraDiDialogoPing;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.UIManager;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 *
 * @author antonio
 */
public class ProjectWizardStep4 extends FinestraDiDialogoPing {

    static {
        setDefaultLookAndFeelDecorated(true);
        setlookAndFeel();
    }

    private static void setlookAndFeel() {
        try {
            String lookAndFeelname = UIManager.getSystemLookAndFeelClassName();
            UIManager.setLookAndFeel(lookAndFeelname);
        } catch (Exception ex) {
            System.out.println("Error loading look and feel");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTop = new javax.swing.JPanel();
        panelStep = new javax.swing.JPanel();
        labelSteps = new javax.swing.JLabel();
        separatorTop1 = new javax.swing.JSeparator();
        labelStep1 = new javax.swing.JLabel();
        labelStep2 = new javax.swing.JLabel();
        labelStep3 = new javax.swing.JLabel();
        labelImg = new javax.swing.JLabel();
        labelStep4 = new javax.swing.JLabel();
        panelData = new javax.swing.JPanel();
        separatorTop2 = new javax.swing.JSeparator();
        labelStepName = new javax.swing.JLabel();
        labelComboTools = new javax.swing.JLabel();
        fieldGenerated = new javax.swing.JTextField();
        labelGenerated = new javax.swing.JLabel();
        buttonFileGenerated = new javax.swing.JButton();
        fieldMapping = new javax.swing.JTextField();
        labelMapping = new javax.swing.JLabel();
        buttonMappingFile = new javax.swing.JButton();
        comboTools = new javax.swing.JComboBox();
        labelNote = new javax.swing.JLabel();
        fieldScript = new javax.swing.JTextField();
        buttonFileScript = new javax.swing.JButton();
        labelScript = new javax.swing.JLabel();
        panelBottom = new javax.swing.JPanel();
        separatorBottom = new javax.swing.JSeparator();
        buttonCancel = new javax.swing.JButton();
        buttonNext = new javax.swing.JButton();
        buttonBack = new javax.swing.JButton();
        buttonFinish = new javax.swing.JButton();

        panelTop.setAlignmentX(0.0F);
        panelTop.setPreferredSize(new java.awt.Dimension(600, 370));

        panelStep.setAlignmentX(0.0F);
        panelStep.setAlignmentY(0.0F);
        panelStep.setFont(panelStep.getFont());
        panelStep.setPreferredSize(new java.awt.Dimension(280, 370));

        labelSteps.setFont(labelSteps.getFont().deriveFont(labelSteps.getFont().getStyle() | java.awt.Font.BOLD));
        labelSteps.setText("Steps");

        separatorTop1.setBackground(new java.awt.Color(240, 240, 240));
        separatorTop1.setPreferredSize(new java.awt.Dimension(242, 6));

        labelStep1.setFont(labelStep1.getFont().deriveFont(labelStep1.getFont().getStyle() & ~java.awt.Font.BOLD));
        labelStep1.setText("Step 1- Project Data");

        labelStep2.setFont(labelStep2.getFont().deriveFont(labelStep2.getFont().getStyle() & ~java.awt.Font.BOLD));
        labelStep2.setText("Step 2 - Mapping Data");
        labelStep2.setMaximumSize(new java.awt.Dimension(143, 7));
        labelStep2.setMinimumSize(new java.awt.Dimension(143, 7));
        labelStep2.setPreferredSize(new java.awt.Dimension(228, 7));

        labelStep3.setFont(labelStep3.getFont().deriveFont(labelStep3.getFont().getStyle() & ~java.awt.Font.BOLD));
        labelStep3.setText("Step 3 - Instances Data");
        labelStep3.setMaximumSize(new java.awt.Dimension(143, 7));
        labelStep3.setMinimumSize(new java.awt.Dimension(143, 7));
        labelStep3.setPreferredSize(new java.awt.Dimension(143, 7));

        labelImg.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        labelStep4.setFont(labelStep4.getFont().deriveFont(labelStep4.getFont().getStyle() | java.awt.Font.BOLD));
        labelStep4.setText("Step 4 - Add Tool >>");
        labelStep4.setMaximumSize(new java.awt.Dimension(143, 7));
        labelStep4.setMinimumSize(new java.awt.Dimension(143, 7));
        labelStep4.setPreferredSize(new java.awt.Dimension(143, 7));

        javax.swing.GroupLayout panelStepLayout = new javax.swing.GroupLayout(panelStep);
        panelStep.setLayout(panelStepLayout);
        panelStepLayout.setHorizontalGroup(
            panelStepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStepLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelStepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separatorTop1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSteps, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelStep1)
                    .addComponent(labelStep3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelStep2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelStep4, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
            .addGroup(panelStepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelStepLayout.createSequentialGroup()
                    .addComponent(labelImg)
                    .addGap(0, 286, Short.MAX_VALUE)))
        );
        panelStepLayout.setVerticalGroup(
            panelStepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStepLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelSteps)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separatorTop1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelStep1)
                .addGap(35, 35, 35)
                .addComponent(labelStep2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(labelStep3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(labelStep4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelStepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelStepLayout.createSequentialGroup()
                    .addComponent(labelImg, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );

        panelData.setMinimumSize(new java.awt.Dimension(320, 370));
        panelData.setPreferredSize(new java.awt.Dimension(320, 370));

        separatorTop2.setBackground(new java.awt.Color(240, 240, 240));
        separatorTop2.setOpaque(true);
        separatorTop2.setPreferredSize(new java.awt.Dimension(300, 6));

        labelStepName.setFont(labelStepName.getFont());
        labelStepName.setText("Step 4 - Add Tool");

        labelComboTools.setFont(labelComboTools.getFont());
        labelComboTools.setText("Mapping Tool:");

        fieldGenerated.setFont(fieldGenerated.getFont());
        fieldGenerated.setMinimumSize(new java.awt.Dimension(6, 25));
        fieldGenerated.setName("fieldTranslatedStep"); // NOI18N
        fieldGenerated.setPreferredSize(new java.awt.Dimension(6, 25));

        labelGenerated.setFont(labelGenerated.getFont());
        labelGenerated.setText("Generated Instance:");

        buttonFileGenerated.setFont(buttonFileGenerated.getFont());
        buttonFileGenerated.setText("...");
        buttonFileGenerated.setMaximumSize(new java.awt.Dimension(71, 25));
        buttonFileGenerated.setMinimumSize(new java.awt.Dimension(71, 25));
        buttonFileGenerated.setName("buttonFileTranslatedStep"); // NOI18N
        buttonFileGenerated.setPreferredSize(new java.awt.Dimension(71, 25));

        fieldMapping.setFont(fieldMapping.getFont());
        fieldMapping.setMinimumSize(new java.awt.Dimension(6, 25));
        fieldMapping.setName("fieldMappingStep"); // NOI18N
        fieldMapping.setPreferredSize(new java.awt.Dimension(6, 25));

        labelMapping.setFont(labelMapping.getFont());
        labelMapping.setText("Mapping File:");

        buttonMappingFile.setFont(buttonMappingFile.getFont());
        buttonMappingFile.setText("...");
        buttonMappingFile.setMaximumSize(new java.awt.Dimension(71, 25));
        buttonMappingFile.setMinimumSize(new java.awt.Dimension(71, 25));
        buttonMappingFile.setName("buttonFileMappingStep"); // NOI18N
        buttonMappingFile.setPreferredSize(new java.awt.Dimension(71, 25));

        comboTools.setFont(comboTools.getFont());
        comboTools.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboTools.setSelectedIndex(-1);
        comboTools.setToolTipText("");
        comboTools.setName("comboToolsStep"); // NOI18N

        labelNote.setFont(labelNote.getFont().deriveFont(labelNote.getFont().getSize()-2f));
        labelNote.setText("<html><P ALIGN=\"justify\">Note: <br>For quality measure we compare Generated Instance wrt Expected Target Instance.</P>");
        labelNote.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        fieldScript.setFont(fieldScript.getFont());
        fieldScript.setMinimumSize(new java.awt.Dimension(6, 25));
        fieldScript.setName("fieldScriptStep"); // NOI18N
        fieldScript.setPreferredSize(new java.awt.Dimension(6, 25));

        buttonFileScript.setFont(buttonFileScript.getFont());
        buttonFileScript.setText("...");
        buttonFileScript.setMaximumSize(new java.awt.Dimension(71, 25));
        buttonFileScript.setMinimumSize(new java.awt.Dimension(71, 25));
        buttonFileScript.setName("buttonFileScriptStep"); // NOI18N
        buttonFileScript.setPreferredSize(new java.awt.Dimension(71, 25));

        labelScript.setFont(labelScript.getFont());
        labelScript.setText("Script File:");

        javax.swing.GroupLayout panelDataLayout = new javax.swing.GroupLayout(panelData);
        panelData.setLayout(panelDataLayout);
        panelDataLayout.setHorizontalGroup(
            panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataLayout.createSequentialGroup()
                .addGroup(panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDataLayout.createSequentialGroup()
                        .addComponent(fieldGenerated, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonFileGenerated, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelDataLayout.createSequentialGroup()
                        .addComponent(fieldMapping, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonMappingFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelDataLayout.createSequentialGroup()
                        .addComponent(labelComboTools)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboTools, 0, 244, Short.MAX_VALUE))
                    .addGroup(panelDataLayout.createSequentialGroup()
                        .addComponent(fieldScript, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonFileScript, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelDataLayout.createSequentialGroup()
                        .addGroup(panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelStepName)
                            .addComponent(labelGenerated)
                            .addComponent(labelMapping)
                            .addComponent(labelScript))
                        .addGap(0, 222, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelDataLayout.createSequentialGroup()
                .addComponent(separatorTop2, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                .addGap(20, 20, 20))
            .addGroup(panelDataLayout.createSequentialGroup()
                .addComponent(labelNote, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelDataLayout.setVerticalGroup(
            panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelStepName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separatorTop2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelComboTools)
                    .addComponent(comboTools, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(labelMapping)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonMappingFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldMapping, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(labelGenerated)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonFileGenerated, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldGenerated, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(labelScript)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonFileScript, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldScript, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout panelTopLayout = new javax.swing.GroupLayout(panelTop);
        panelTop.setLayout(panelTopLayout);
        panelTopLayout.setHorizontalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTopLayout.createSequentialGroup()
                .addComponent(panelStep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelData, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE))
        );
        panelTopLayout.setVerticalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelStep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelBottom.setAlignmentX(0.0F);
        panelBottom.setAlignmentY(0.0F);
        panelBottom.setPreferredSize(new java.awt.Dimension(600, 50));

        separatorBottom.setBackground(new java.awt.Color(240, 240, 240));
        separatorBottom.setAlignmentY(0.0F);
        separatorBottom.setPreferredSize(new java.awt.Dimension(600, 6));

        buttonCancel.setFont(buttonCancel.getFont());
        buttonCancel.setText("Cancel");

        buttonNext.setFont(buttonNext.getFont());
        buttonNext.setText("Next >");

        buttonBack.setFont(buttonBack.getFont());
        buttonBack.setText("< Back");

        buttonFinish.setFont(buttonFinish.getFont());
        buttonFinish.setText("Finish");

        javax.swing.GroupLayout panelBottomLayout = new javax.swing.GroupLayout(panelBottom);
        panelBottom.setLayout(panelBottomLayout);
        panelBottomLayout.setHorizontalGroup(
            panelBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separatorBottom, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
            .addGroup(panelBottomLayout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(buttonBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(buttonNext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(buttonFinish, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(buttonCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelBottomLayout.setVerticalGroup(
            panelBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBottomLayout.createSequentialGroup()
                .addComponent(separatorBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(panelBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonBack)
                    .addGroup(panelBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonNext)
                        .addComponent(buttonFinish))
                    .addComponent(buttonCancel))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTop, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
            .addComponent(panelBottom, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonFileGenerated;
    private javax.swing.JButton buttonFileScript;
    private javax.swing.JButton buttonFinish;
    private javax.swing.JButton buttonMappingFile;
    private javax.swing.JButton buttonNext;
    private javax.swing.JComboBox comboTools;
    private javax.swing.JTextField fieldGenerated;
    private javax.swing.JTextField fieldMapping;
    private javax.swing.JTextField fieldScript;
    private javax.swing.JLabel labelComboTools;
    private javax.swing.JLabel labelGenerated;
    private javax.swing.JLabel labelImg;
    private javax.swing.JLabel labelMapping;
    private javax.swing.JLabel labelNote;
    private javax.swing.JLabel labelScript;
    private javax.swing.JLabel labelStep1;
    private javax.swing.JLabel labelStep2;
    private javax.swing.JLabel labelStep3;
    private javax.swing.JLabel labelStep4;
    private javax.swing.JLabel labelStepName;
    private javax.swing.JLabel labelSteps;
    private javax.swing.JPanel panelBottom;
    private javax.swing.JPanel panelData;
    private javax.swing.JPanel panelStep;
    private javax.swing.JPanel panelTop;
    private javax.swing.JSeparator separatorBottom;
    private javax.swing.JSeparator separatorTop1;
    private javax.swing.JSeparator separatorTop2;
    // End of variables declaration//GEN-END:variables
    private Log logger = LogFactory.getLog(this.getClass());

    @Override
    public void inizializza() {
        initComponents();
        this.setDefaultCloseOperation(HIDE_ON_CLOSE);
        //this.setSize(600, 455);
        this.setResizable(false);
        this.setModal(true);
        this.setTitle("New Project");
        this.createForm();
        this.postInit();
        this.pack();
    }
 

    @SuppressWarnings("unchecked")
    public void buildCombo() {
        this.comboTools.removeAllItems();
        List<String> tools = (List<String>) this.modello.getBean(Constant.TOOLS_LIST_NEW);
        for (String string : tools) {
            comboTools.addItem(string.replace("_", " "));
        }
        int index = (Integer) modello.getBean(Constant.COMBO_TOOL_SELECTED_INDEX);
        comboTools.setSelectedIndex(index);
        logger.trace("Step4 Selected Tools: " + comboTools.getSelectedIndex() + " select: " + modello.getBean(Constant.COMBO_TOOL_SELECTED_INDEX));
    }

    private void createForm() {
        IForm form = new Form(this);
        //tool name
        //ICollegatore collTool = new CollegatoreComboBox(form, this.comboTools, Constant.TOOL_NEW, MappingTool.class, "toolName");
        ICollegatore collTool = new CollegatoreComboBox(form, this.comboTools, Constant.TOOL_NEW, MappingToolPM.class, "toolName");
        //mapping file
        //IOsservatore obsMapping = new OsservatoreTextField(Constant.FIELD_FILE_MAPPING_STEP, Constant.TOOL_NEW, MappingTool.class, "mappingPath");
        IOsservatore obsMapping = new OsservatoreTextField(Constant.FIELD_FILE_MAPPING_STEP, Constant.TOOL_NEW, MappingToolPM.class, "mappingPath");
        //ICollegatore collMapping = new CollegatoreTextField(form, Constant.FIELD_FILE_MAPPING_STEP, Constant.TOOL_NEW, MappingTool.class, "mappingPath");
        ICollegatore collMapping = new CollegatoreTextField(form, Constant.FIELD_FILE_MAPPING_STEP, Constant.TOOL_NEW, MappingToolPM.class, "mappingPath");
        IConvalidatoreValore convMapping = createFieldValidator(Constant.FIELD_FILE_MAPPING_STEP, "Mapping Task");
        collMapping.addConvalidatore(convMapping);
        //file instances generated
        //IOsservatore obsTranslated = new OsservatoreTextField(Constant.FIELD_FILE_TRANSLATED_STEP, Constant.TOOL_NEW, MappingTool.class, "translatedInstance");
        IOsservatore obsTranslated = new OsservatoreTextField(Constant.FIELD_FILE_TRANSLATED_STEP, Constant.TOOL_NEW, MappingToolPM.class, "translatedInstance");
        //ICollegatore collTranslated = new CollegatoreTextField(form, Constant.FIELD_FILE_TRANSLATED_STEP, Constant.TOOL_NEW, MappingTool.class, "translatedInstance");
        ICollegatore collTranslated = new CollegatoreTextField(form, Constant.FIELD_FILE_TRANSLATED_STEP, Constant.TOOL_NEW, MappingToolPM.class, "translatedInstance");
        IConvalidatoreValore convTranslated = createFieldValidator(Constant.FIELD_FILE_TRANSLATED_STEP, "Generated Instance");
        collTranslated.addConvalidatore(convTranslated);

        //file script
        IOsservatore obsScript = new OsservatoreTextField(Constant.FIELD_FILE_SCRIPT_STEP, Constant.TOOL_NEW, MappingToolPM.class, "scriptFile");
        //IOsservatore obsScript = new OsservatoreTextField(Constant.FIELD_FILE_SCRIPT_STEP, Constant.TOOL_NEW, MappingTool.class, "scriptFile");
        ICollegatore collScript = new CollegatoreTextField(form, Constant.FIELD_FILE_SCRIPT_STEP, Constant.TOOL_NEW, MappingToolPM.class, "scriptFile");
        //ICollegatore collScript = new CollegatoreTextField(form, Constant.FIELD_FILE_SCRIPT_STEP, Constant.TOOL_NEW, MappingTool.class, "scriptFile");

        form.setBottoneCommit(this.buttonFinish, ActionFinishStep4.class.getName());
        form.setBottoneRollback(this.buttonCancel);
        form.setBottoneIndietro(this.buttonBack, ActionBackStep4.class.getName());
    }

    private IConvalidatoreValore createFieldValidator(String field, final String message) {
        return new ConvalidatoreValoreAstratto(field) {
            @Override
            public List convalida(Object o) {
                String name = (String) o;
                List<String> errors = new ArrayList<String>();
                if (name.equals("")) {
                    errors.add("The data value " + message + " can not be empty");
                } else if (message.equals("Mapping Task")) {
                    String tool = (String) modello.getBean(Constant.COMBO_TOOL_SELECTED);
                    if (!Utils.convalidateFormatFile(tool, name)) {
                        errors.add("The File for data value " + message + " is not valid");
                    }
                } else if (!name.contains(File.separator)) {
                    errors.add("Path for data value " + message + " is not valid");
                }
                return errors;
            }

            @Override
            public Object converti(Object o) {
                return o;
            }
        };
    }

    private void postInit() {
        this.buttonFileGenerated.setAction(this.controllo.getAzioneSwing(ActionChooseFile.class.getName()));
        this.buttonMappingFile.setAction(this.controllo.getAzioneSwing(ActionChooseFile.class.getName()));
        this.buttonFileScript.setAction(this.controllo.getAzioneSwing(ActionChooseFile.class.getName()));
        this.labelImg.setIcon(Utils.createImage(Constant.WIZARD_IMG));
        this.comboTools.setAction(this.controllo.getAzioneSwing(ActionSelectTool.class.getName()));
        this.buttonFinish.setEnabled(true);
        this.buttonNext.setEnabled(false);
        this.comboTools.setToolTipText(Constant.TOOLTIP_TOOL_NAME);
        this.fieldMapping.setToolTipText(Constant.TOOLTIP_TOOL_MAPPING_FILE);
        this.fieldGenerated.setToolTipText(Constant.TOOLTIP_TOOL_INSTANCE_GENERATED);
        this.fieldScript.setToolTipText(Constant.TOOLTIP_TOOL_SCRIPT);
    }

    @Override
    public void visualizza() {
        FinestraDiDialogoPing dialog3 = (FinestraDiDialogoPing) this.vista.getSottoVista(ProjectWizardStep3.class.getName());
        this.setLocation(dialog3.getLocation());
        super.visualizza();
    }
}
