/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package it.unibas.iqmeter.view.wizard;

import it.unibas.iqmeter.Constant;
import it.unibas.iqmeter.Utils;
import it.unibas.iqmeter.controller.ActionChooseFolder;
import it.unibas.iqmeter.controller.wizard.ActionNextStep1;
import it.unibas.iqmeter.model.Scenario;
import it.unibas.iqmeter.view.presentationmodel.ScenarioPM;
import it.unibas.ping.binding.Form;
import it.unibas.ping.binding.IForm;
import it.unibas.ping.binding.collegatori.CollegatoreTextField;
import it.unibas.ping.binding.collegatori.ICollegatore;
import it.unibas.ping.binding.osservatori.IOsservatore;
import it.unibas.ping.binding.osservatori.OsservatoreTextField;
import it.unibas.ping.convalida.ConvalidatoreValoreAstratto;
import it.unibas.ping.convalida.IConvalidatoreValore;
import it.unibas.ping.framework.FinestraDiDialogoPing;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.UIManager;

/**
 *
 * @author antonio
 */
public class ProjectWizardStep1 extends FinestraDiDialogoPing {

    static {
        setDefaultLookAndFeelDecorated(true);
        setlookAndFeel();
    }

    private static void setlookAndFeel() {
        try {
            String lookAndFeelname = UIManager.getSystemLookAndFeelClassName();

            UIManager.setLookAndFeel(lookAndFeelname);
        } catch (Exception ex) {
            System.out.println("Error loading look and feel");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTop = new javax.swing.JPanel();
        panelStep = new javax.swing.JPanel();
        labelSteps = new javax.swing.JLabel();
        separatorTop1 = new javax.swing.JSeparator();
        labelStep1 = new javax.swing.JLabel();
        labelStep2 = new javax.swing.JLabel();
        labelStep3 = new javax.swing.JLabel();
        labelImg = new javax.swing.JLabel();
        labelStep4 = new javax.swing.JLabel();
        panelData = new javax.swing.JPanel();
        labelName = new javax.swing.JLabel();
        separatorTop2 = new javax.swing.JSeparator();
        labelStepName = new javax.swing.JLabel();
        fieldName = new javax.swing.JTextField();
        labelOutput = new javax.swing.JLabel();
        fieldOutput = new javax.swing.JTextField();
        buttonFolderWizard = new javax.swing.JButton();
        panelBottom = new javax.swing.JPanel();
        separatorBottom = new javax.swing.JSeparator();
        buttonCancel = new javax.swing.JButton();
        buttonNext = new javax.swing.JButton();
        buttonBack = new javax.swing.JButton();
        buttonFinish = new javax.swing.JButton();

        panelTop.setAlignmentX(0.0F);
        panelTop.setPreferredSize(new java.awt.Dimension(600, 370));

        panelStep.setAlignmentX(0.0F);
        panelStep.setAlignmentY(0.0F);
        panelStep.setFont(panelStep.getFont());
        panelStep.setPreferredSize(new java.awt.Dimension(280, 370));

        labelSteps.setFont(labelSteps.getFont().deriveFont(labelSteps.getFont().getStyle() | java.awt.Font.BOLD));
        labelSteps.setText("Steps");

        separatorTop1.setBackground(new java.awt.Color(240, 240, 240));
        separatorTop1.setPreferredSize(new java.awt.Dimension(242, 6));

        labelStep1.setFont(labelStep1.getFont().deriveFont(labelStep1.getFont().getStyle() | java.awt.Font.BOLD));
        labelStep1.setText("Step 1- Project Data >>");

        labelStep2.setFont(labelStep2.getFont().deriveFont(labelStep2.getFont().getStyle() & ~java.awt.Font.BOLD));
        labelStep2.setText("Step 2 - Mapping Data");
        labelStep2.setMaximumSize(new java.awt.Dimension(143, 7));
        labelStep2.setMinimumSize(new java.awt.Dimension(143, 7));
        labelStep2.setPreferredSize(new java.awt.Dimension(228, 7));

        labelStep3.setFont(labelStep3.getFont().deriveFont(labelStep3.getFont().getStyle() & ~java.awt.Font.BOLD));
        labelStep3.setText("Step 3 - Instances Data ");
        labelStep3.setMaximumSize(new java.awt.Dimension(143, 7));
        labelStep3.setMinimumSize(new java.awt.Dimension(143, 7));
        labelStep3.setPreferredSize(new java.awt.Dimension(143, 7));

        labelImg.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        labelStep4.setFont(labelStep4.getFont().deriveFont(labelStep4.getFont().getStyle() & ~java.awt.Font.BOLD));
        labelStep4.setText("Step 4 - Add Tool");
        labelStep4.setMaximumSize(new java.awt.Dimension(143, 7));
        labelStep4.setMinimumSize(new java.awt.Dimension(143, 7));
        labelStep4.setPreferredSize(new java.awt.Dimension(143, 7));

        javax.swing.GroupLayout panelStepLayout = new javax.swing.GroupLayout(panelStep);
        panelStep.setLayout(panelStepLayout);
        panelStepLayout.setHorizontalGroup(
            panelStepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStepLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelStepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separatorTop1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSteps, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelStep1)
                    .addComponent(labelStep3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelStep2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelStep4, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
            .addGroup(panelStepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelStepLayout.createSequentialGroup()
                    .addComponent(labelImg)
                    .addGap(0, 286, Short.MAX_VALUE)))
        );
        panelStepLayout.setVerticalGroup(
            panelStepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStepLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelSteps)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separatorTop1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelStep1)
                .addGap(35, 35, 35)
                .addComponent(labelStep2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(labelStep3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(labelStep4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
            .addGroup(panelStepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelStepLayout.createSequentialGroup()
                    .addComponent(labelImg, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panelData.setMinimumSize(new java.awt.Dimension(320, 370));
        panelData.setPreferredSize(new java.awt.Dimension(320, 370));

        labelName.setFont(labelName.getFont());
        labelName.setText("Project Name:");

        separatorTop2.setBackground(new java.awt.Color(240, 240, 240));
        separatorTop2.setPreferredSize(new java.awt.Dimension(300, 6));

        labelStepName.setFont(labelStepName.getFont());
        labelStepName.setText("Step 1 - Project Data");

        fieldName.setFont(fieldName.getFont());
        fieldName.setMinimumSize(new java.awt.Dimension(6, 25));
        fieldName.setName("fieldName"); // NOI18N
        fieldName.setPreferredSize(new java.awt.Dimension(6, 25));
        fieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNameActionPerformed(evt);
            }
        });

        labelOutput.setFont(labelOutput.getFont());
        labelOutput.setText("Output Project Folder :");

        fieldOutput.setFont(fieldOutput.getFont());
        fieldOutput.setMinimumSize(new java.awt.Dimension(6, 25));
        fieldOutput.setName("fieldOutput"); // NOI18N
        fieldOutput.setPreferredSize(new java.awt.Dimension(6, 25));

        buttonFolderWizard.setFont(buttonFolderWizard.getFont());
        buttonFolderWizard.setText("...");
        buttonFolderWizard.setMaximumSize(new java.awt.Dimension(71, 25));
        buttonFolderWizard.setMinimumSize(new java.awt.Dimension(71, 25));
        buttonFolderWizard.setName("buttonFolderWizard"); // NOI18N
        buttonFolderWizard.setPreferredSize(new java.awt.Dimension(71, 25));

        javax.swing.GroupLayout panelDataLayout = new javax.swing.GroupLayout(panelData);
        panelData.setLayout(panelDataLayout);
        panelDataLayout.setHorizontalGroup(
            panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelStepName, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                    .addGroup(panelDataLayout.createSequentialGroup()
                        .addComponent(labelName)
                        .addGap(18, 18, 18)
                        .addComponent(fieldName, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))
                    .addGroup(panelDataLayout.createSequentialGroup()
                        .addComponent(fieldOutput, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonFolderWizard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(separatorTop2, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                    .addComponent(labelOutput))
                .addGap(26, 26, 26))
        );
        panelDataLayout.setVerticalGroup(
            panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelStepName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separatorTop2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelName)
                    .addComponent(fieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(labelOutput)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonFolderWizard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(188, 188, 188))
        );

        javax.swing.GroupLayout panelTopLayout = new javax.swing.GroupLayout(panelTop);
        panelTop.setLayout(panelTopLayout);
        panelTopLayout.setHorizontalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTopLayout.createSequentialGroup()
                .addComponent(panelStep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelData, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE))
        );
        panelTopLayout.setVerticalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelStep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panelData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panelBottom.setAlignmentX(0.0F);
        panelBottom.setAlignmentY(0.0F);
        panelBottom.setPreferredSize(new java.awt.Dimension(600, 50));

        separatorBottom.setBackground(new java.awt.Color(240, 240, 240));
        separatorBottom.setAlignmentY(0.0F);
        separatorBottom.setPreferredSize(new java.awt.Dimension(600, 6));

        buttonCancel.setFont(buttonCancel.getFont());
        buttonCancel.setText("Cancel");

        buttonNext.setFont(buttonNext.getFont());
        buttonNext.setText("Next >");

        buttonBack.setFont(buttonBack.getFont());
        buttonBack.setText("< Back");

        buttonFinish.setFont(buttonFinish.getFont());
        buttonFinish.setText("Finish");

        javax.swing.GroupLayout panelBottomLayout = new javax.swing.GroupLayout(panelBottom);
        panelBottom.setLayout(panelBottomLayout);
        panelBottomLayout.setHorizontalGroup(
            panelBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBottomLayout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(buttonBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(buttonNext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(buttonFinish, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(buttonCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(separatorBottom, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );
        panelBottomLayout.setVerticalGroup(
            panelBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBottomLayout.createSequentialGroup()
                .addComponent(separatorBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonNext)
                    .addComponent(buttonBack)
                    .addComponent(buttonCancel)
                    .addComponent(buttonFinish))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTop, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
            .addComponent(panelBottom, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNameActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonFinish;
    private javax.swing.JButton buttonFolderWizard;
    private javax.swing.JButton buttonNext;
    private javax.swing.JTextField fieldName;
    private javax.swing.JTextField fieldOutput;
    private javax.swing.JLabel labelImg;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelOutput;
    private javax.swing.JLabel labelStep1;
    private javax.swing.JLabel labelStep2;
    private javax.swing.JLabel labelStep3;
    private javax.swing.JLabel labelStep4;
    private javax.swing.JLabel labelStepName;
    private javax.swing.JLabel labelSteps;
    private javax.swing.JPanel panelBottom;
    private javax.swing.JPanel panelData;
    private javax.swing.JPanel panelStep;
    private javax.swing.JPanel panelTop;
    private javax.swing.JSeparator separatorBottom;
    private javax.swing.JSeparator separatorTop1;
    private javax.swing.JSeparator separatorTop2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void inizializza() {
        initComponents();
        this.setDefaultCloseOperation(HIDE_ON_CLOSE);
        this.setResizable(false);
        this.setModal(true);
        this.setTitle("New Project");
        this.createForm();
        this.postInit();
        //this.setSize(600, 420);
        this.pack();

    }

    private void createForm() {
        IForm formStep1 = new Form(this);

        //name
        IOsservatore obsName = new OsservatoreTextField(Constant.FIELD_PROJECT_NAME, Constant.SCENARIO_NEW, "name");
        ICollegatore collName = new CollegatoreTextField(formStep1, obsName);
        IConvalidatoreValore convName = createFieldValidator(Constant.FIELD_PROJECT_NAME, "Project Name");
        collName.addConvalidatore(convName);

//        //tool
//        IOsservatore obsTool = new OsservatoreComboBox("comboTool", Constant.SCENARIO_NEW, "toolName");
//        ICollegatore collTool = new CollegatoreComboBox(formStep1, obsTool);

        //out path 
        //IOsservatore obsOut = new OsservatoreTextField(Constant.FIELD_OUTPUT_FOLDER, Constant.SCENARIO_NEW, Scenario.class, "outputFolder");
        IOsservatore obsOut = new OsservatoreTextField(Constant.FIELD_OUTPUT_FOLDER, Constant.SCENARIO_NEW, ScenarioPM.class, "outputFolder");
        ICollegatore collOut = new CollegatoreTextField(formStep1, obsOut);
        IConvalidatoreValore convOut = createFieldValidator(Constant.FIELD_OUTPUT_FOLDER, "Output Folder");
        collOut.addConvalidatore(convOut);

        formStep1.setBottoneAvanti(this.buttonNext, ActionNextStep1.class.getName());
        formStep1.setBottoneRollback(this.buttonCancel);

    }

    private IConvalidatoreValore createFieldValidator(final String fieldName, final String message) {
        return new ConvalidatoreValoreAstratto("fieldName") {
            @Override
            public List convalida(Object o) {
                String name = (String) o;
                List<String> errors = new ArrayList<String>();
                if (name.equals("")) {
                    errors.add("The data value " + message + " can not be empty");
                }else if(fieldName.equals(Constant.FIELD_OUTPUT_FOLDER)){
                    if(!new File(name).isDirectory()){
                        errors.add("The data value " + message + " is not an existing directory");
                    }
                }
                
                return errors;
            }

            @Override
            public Object converti(Object o) {
                return o;
            }
        };
    }

    private void postInit() {
        this.buttonBack.setEnabled(false);
        this.buttonFinish.setEnabled(false);
        this.buttonFolderWizard.setAction(this.controllo.getAzioneSwing(ActionChooseFolder.class.getName()));
        this.labelImg.setIcon(Utils.createImage(Constant.WIZARD_IMG));
        this.fieldName.setToolTipText(Constant.TOOLTIP_NAME);
        this.fieldOutput.setToolTipText(Constant.TOOLTIP_FOLDER);
    }

    @Override
    public void visualizza() {
        this.setLocationRelativeTo(this.vista.getFramePrincipale());
        super.visualizza();
    }

    public void visualizzaBack() {
        FinestraDiDialogoPing dialog2 = (FinestraDiDialogoPing) this.vista.getSottoVista(ProjectWizardStep2.class.getName());
        this.setLocation(dialog2.getLocation());
        super.visualizza();
    }
}
