/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package it.unibas.iqmeter.view.wizard;

import it.unibas.iqmeter.Constant;
import it.unibas.iqmeter.Utils;
import it.unibas.iqmeter.controller.ActionChooseFile;
import it.unibas.iqmeter.controller.wizard.ActionActiveTargetFile;
import it.unibas.iqmeter.controller.wizard.ActionBackStep3;
import it.unibas.iqmeter.controller.wizard.ActionCancel;
import it.unibas.iqmeter.controller.wizard.ActionNextStep3;
import it.unibas.iqmeter.model.Scenario;
import it.unibas.iqmeter.persistence.PropertiesLoader;
import it.unibas.ping.binding.Form;
import it.unibas.ping.binding.IForm;
import it.unibas.ping.binding.collegatori.CollegatoreTextField;
import it.unibas.ping.binding.collegatori.ICollegatore;
import it.unibas.ping.binding.osservatori.IOsservatore;
import it.unibas.ping.binding.osservatori.OsservatoreTextField;
import it.unibas.ping.convalida.ConvalidatoreValoreAstratto;
import it.unibas.ping.convalida.IConvalidatoreValore;
import it.unibas.ping.framework.FinestraDiDialogoPing;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.UIManager;

/**
 *
 * @author antonio
 */
public class ProjectWizardStep3 extends FinestraDiDialogoPing {

    private String standardFeatures = "";

    static {
        setDefaultLookAndFeelDecorated(true);
        setlookAndFeel();
    }

    private static void setlookAndFeel() {
        try {
            String lookAndFeelname = UIManager.getSystemLookAndFeelClassName();
            UIManager.setLookAndFeel(lookAndFeelname);
        } catch (Exception ex) {
            System.out.println("Error loading look and feel");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTop = new javax.swing.JPanel();
        panelStep = new javax.swing.JPanel();
        labelSteps = new javax.swing.JLabel();
        separatorTop1 = new javax.swing.JSeparator();
        labelStep1 = new javax.swing.JLabel();
        labelStep2 = new javax.swing.JLabel();
        labelStep3 = new javax.swing.JLabel();
        labelImg = new javax.swing.JLabel();
        labelStep4 = new javax.swing.JLabel();
        panelData = new javax.swing.JPanel();
        separatorTop2 = new javax.swing.JSeparator();
        labelStepName = new javax.swing.JLabel();
        labelFeatures = new javax.swing.JLabel();
        scrollPaneFeatures = new javax.swing.JScrollPane();
        textAreaFeatures = new javax.swing.JTextArea();
        scrollPaneExclusionsList = new javax.swing.JScrollPane();
        textAreaExclusionsList = new javax.swing.JTextArea();
        labelExclusionsList = new javax.swing.JLabel();
        labelExclusionsFile = new javax.swing.JLabel();
        fieldExclusions = new javax.swing.JTextField();
        radioButtonExclusions = new javax.swing.JRadioButton();
        buttonFileExclusions = new javax.swing.JButton();
        panelBottom = new javax.swing.JPanel();
        separatorBottom = new javax.swing.JSeparator();
        buttonCancel = new javax.swing.JButton();
        buttonNext = new javax.swing.JButton();
        buttonBack = new javax.swing.JButton();
        buttonFinish = new javax.swing.JButton();

        panelTop.setAlignmentX(0.0F);
        panelTop.setPreferredSize(new java.awt.Dimension(600, 370));

        panelStep.setAlignmentX(0.0F);
        panelStep.setAlignmentY(0.0F);
        panelStep.setFont(panelStep.getFont());
        panelStep.setPreferredSize(new java.awt.Dimension(280, 370));

        labelSteps.setFont(labelSteps.getFont().deriveFont(labelSteps.getFont().getStyle() | java.awt.Font.BOLD));
        labelSteps.setText("Steps");

        separatorTop1.setBackground(new java.awt.Color(240, 240, 240));
        separatorTop1.setPreferredSize(new java.awt.Dimension(242, 6));

        labelStep1.setFont(labelStep1.getFont().deriveFont(labelStep1.getFont().getStyle() & ~java.awt.Font.BOLD));
        labelStep1.setText("Step 1- Project Data");

        labelStep2.setFont(labelStep2.getFont().deriveFont(labelStep2.getFont().getStyle() & ~java.awt.Font.BOLD));
        labelStep2.setText("Step 2 - Mapping Data");
        labelStep2.setMaximumSize(new java.awt.Dimension(143, 7));
        labelStep2.setMinimumSize(new java.awt.Dimension(143, 7));
        labelStep2.setPreferredSize(new java.awt.Dimension(228, 7));

        labelStep3.setFont(labelStep3.getFont().deriveFont(labelStep3.getFont().getStyle() | java.awt.Font.BOLD));
        labelStep3.setText("Step 3 - Instances Data >>");
        labelStep3.setMaximumSize(new java.awt.Dimension(143, 7));
        labelStep3.setMinimumSize(new java.awt.Dimension(143, 7));
        labelStep3.setPreferredSize(new java.awt.Dimension(143, 7));

        labelImg.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        labelStep4.setFont(labelStep4.getFont().deriveFont(labelStep4.getFont().getStyle() & ~java.awt.Font.BOLD));
        labelStep4.setText("Step 4 - Add Tool");
        labelStep4.setMaximumSize(new java.awt.Dimension(143, 7));
        labelStep4.setMinimumSize(new java.awt.Dimension(143, 7));
        labelStep4.setPreferredSize(new java.awt.Dimension(143, 7));

        javax.swing.GroupLayout panelStepLayout = new javax.swing.GroupLayout(panelStep);
        panelStep.setLayout(panelStepLayout);
        panelStepLayout.setHorizontalGroup(
            panelStepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStepLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelStepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separatorTop1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSteps, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelStep1)
                    .addComponent(labelStep3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelStep2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelStep4, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
            .addGroup(panelStepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelStepLayout.createSequentialGroup()
                    .addComponent(labelImg)
                    .addGap(0, 286, Short.MAX_VALUE)))
        );
        panelStepLayout.setVerticalGroup(
            panelStepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStepLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelSteps)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separatorTop1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelStep1)
                .addGap(35, 35, 35)
                .addComponent(labelStep2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(labelStep3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(labelStep4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelStepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelStepLayout.createSequentialGroup()
                    .addComponent(labelImg, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );

        panelData.setMinimumSize(new java.awt.Dimension(320, 370));
        panelData.setPreferredSize(new java.awt.Dimension(320, 370));

        separatorTop2.setBackground(new java.awt.Color(240, 240, 240));
        separatorTop2.setOpaque(true);
        separatorTop2.setPreferredSize(new java.awt.Dimension(300, 6));

        labelStepName.setFont(labelStepName.getFont());
        labelStepName.setText("Step 3 - Mapping Data");

        labelFeatures.setFont(labelFeatures.getFont());
        labelFeatures.setText("Features:");

        scrollPaneFeatures.setPreferredSize(new java.awt.Dimension(242, 60));

        textAreaFeatures.setColumns(20);
        textAreaFeatures.setRows(3);
        textAreaFeatures.setName("textAreaFeatures"); // NOI18N
        scrollPaneFeatures.setViewportView(textAreaFeatures);

        textAreaExclusionsList.setColumns(20);
        textAreaExclusionsList.setRows(3);
        textAreaExclusionsList.setName("textAreaExclusionsList"); // NOI18N
        scrollPaneExclusionsList.setViewportView(textAreaExclusionsList);

        labelExclusionsList.setFont(labelExclusionsList.getFont());
        labelExclusionsList.setText("Exclusions List:");

        labelExclusionsFile.setFont(labelExclusionsFile.getFont());
        labelExclusionsFile.setText("Exclusions List File:");
        labelExclusionsFile.setEnabled(false);

        fieldExclusions.setEnabled(false);
        fieldExclusions.setMinimumSize(new java.awt.Dimension(6, 25));
        fieldExclusions.setName("fieldExclusions"); // NOI18N
        fieldExclusions.setPreferredSize(new java.awt.Dimension(6, 25));

        radioButtonExclusions.setAlignmentY(0.0F);
        radioButtonExclusions.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        radioButtonExclusions.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        radioButtonExclusions.setName("radioButtonExclusions"); // NOI18N
        radioButtonExclusions.setPreferredSize(new java.awt.Dimension(22, 17));
        radioButtonExclusions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonExclusionsActionPerformed(evt);
            }
        });

        buttonFileExclusions.setText("...");
        buttonFileExclusions.setEnabled(false);
        buttonFileExclusions.setMaximumSize(new java.awt.Dimension(71, 25));
        buttonFileExclusions.setMinimumSize(new java.awt.Dimension(71, 25));
        buttonFileExclusions.setName("buttonFileExclusions"); // NOI18N
        buttonFileExclusions.setPreferredSize(new java.awt.Dimension(71, 25));

        javax.swing.GroupLayout panelDataLayout = new javax.swing.GroupLayout(panelData);
        panelData.setLayout(panelDataLayout);
        panelDataLayout.setHorizontalGroup(
            panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataLayout.createSequentialGroup()
                .addGroup(panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDataLayout.createSequentialGroup()
                        .addComponent(fieldExclusions, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonFileExclusions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelDataLayout.createSequentialGroup()
                        .addGroup(panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelStepName)
                            .addComponent(labelFeatures)
                            .addComponent(labelExclusionsList)
                            .addGroup(panelDataLayout.createSequentialGroup()
                                .addComponent(radioButtonExclusions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(labelExclusionsFile)))
                        .addGap(0, 176, Short.MAX_VALUE))
                    .addComponent(scrollPaneExclusionsList, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                    .addComponent(scrollPaneFeatures, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                    .addComponent(separatorTop2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelDataLayout.setVerticalGroup(
            panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelStepName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separatorTop2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelFeatures)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneFeatures, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelExclusionsList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneExclusionsList, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelExclusionsFile)
                    .addComponent(radioButtonExclusions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonFileExclusions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldExclusions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout panelTopLayout = new javax.swing.GroupLayout(panelTop);
        panelTop.setLayout(panelTopLayout);
        panelTopLayout.setHorizontalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTopLayout.createSequentialGroup()
                .addComponent(panelStep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        panelTopLayout.setVerticalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panelStep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelBottom.setAlignmentX(0.0F);
        panelBottom.setAlignmentY(0.0F);
        panelBottom.setPreferredSize(new java.awt.Dimension(600, 50));

        separatorBottom.setBackground(new java.awt.Color(240, 240, 240));
        separatorBottom.setAlignmentY(0.0F);
        separatorBottom.setPreferredSize(new java.awt.Dimension(600, 6));

        buttonCancel.setFont(buttonCancel.getFont());
        buttonCancel.setText("Cancel");

        buttonNext.setFont(buttonNext.getFont());
        buttonNext.setText("Next >");
        buttonNext.setName("buttonNext"); // NOI18N

        buttonBack.setFont(buttonBack.getFont());
        buttonBack.setText("< Back");

        buttonFinish.setFont(buttonFinish.getFont());
        buttonFinish.setText("Finish");

        javax.swing.GroupLayout panelBottomLayout = new javax.swing.GroupLayout(panelBottom);
        panelBottom.setLayout(panelBottomLayout);
        panelBottomLayout.setHorizontalGroup(
            panelBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separatorBottom, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
            .addGroup(panelBottomLayout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(buttonBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(buttonNext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(buttonFinish, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(buttonCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelBottomLayout.setVerticalGroup(
            panelBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBottomLayout.createSequentialGroup()
                .addComponent(separatorBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(panelBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonBack)
                    .addGroup(panelBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonNext)
                        .addComponent(buttonFinish))
                    .addComponent(buttonCancel))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTop, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
            .addComponent(panelBottom, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void radioButtonExclusionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonExclusionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonExclusionsActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonFileExclusions;
    private javax.swing.JButton buttonFinish;
    private javax.swing.JButton buttonNext;
    private javax.swing.JTextField fieldExclusions;
    private javax.swing.JLabel labelExclusionsFile;
    private javax.swing.JLabel labelExclusionsList;
    private javax.swing.JLabel labelFeatures;
    private javax.swing.JLabel labelImg;
    private javax.swing.JLabel labelStep1;
    private javax.swing.JLabel labelStep2;
    private javax.swing.JLabel labelStep3;
    private javax.swing.JLabel labelStep4;
    private javax.swing.JLabel labelStepName;
    private javax.swing.JLabel labelSteps;
    private javax.swing.JPanel panelBottom;
    private javax.swing.JPanel panelData;
    private javax.swing.JPanel panelStep;
    private javax.swing.JPanel panelTop;
    private javax.swing.JRadioButton radioButtonExclusions;
    private javax.swing.JScrollPane scrollPaneExclusionsList;
    private javax.swing.JScrollPane scrollPaneFeatures;
    private javax.swing.JSeparator separatorBottom;
    private javax.swing.JSeparator separatorTop1;
    private javax.swing.JSeparator separatorTop2;
    private javax.swing.JTextArea textAreaExclusionsList;
    private javax.swing.JTextArea textAreaFeatures;
    // End of variables declaration//GEN-END:variables

    @Override
    public void inizializza() {
        initComponents();
        this.setDefaultCloseOperation(HIDE_ON_CLOSE);
        //this.setSize(600, 455);
        this.setResizable(false);
        this.setModal(true);
        this.setTitle("New Project");
        this.createForm();
        this.postInit();
        this.pack();
    }

    private void createForm() {
        IForm formStep3 = new Form(this);
        if (this.fieldExclusions.isEnabled()) {
            IOsservatore obsExclusion = new OsservatoreTextField(Constant.FIELD_FILE_EXCLUSIONS, Constant.SCENARIO_NEW, Scenario.class, "exclusionListPath");
            ICollegatore collExclusion = new CollegatoreTextField(formStep3, obsExclusion);
            IConvalidatoreValore convExclusion = createFieldValidator(Constant.FIELD_FILE_EXCLUSIONS, "Exclusion List");
            collExclusion.addConvalidatore(convExclusion);
        }
        formStep3.setBottoneIndietro(this.buttonBack, ActionBackStep3.class.getName());
        formStep3.setBottoneRollback(this.buttonCancel, ActionCancel.class.getName());
        //formStep3.setBottoneCommit(this.buttonFinish, ActionFinish.class.getName());
        formStep3.setBottoneAvanti(this.buttonNext, ActionNextStep3.class.getName());

    }

    private void postInit() {
        this.radioButtonExclusions.setAction(this.controllo.getAzioneSwing(ActionActiveTargetFile.class.getName()));
        this.buttonFileExclusions.setAction(this.controllo.getAzioneSwing(ActionChooseFile.class.getName()));
        this.buttonFileExclusions.setEnabled(false);
        this.labelImg.setIcon(Utils.createImage(Constant.WIZARD_IMG));
        this.buttonNext.setEnabled(true);
        this.buttonFinish.setEnabled(false);
        this.loadFeatures();
        this.fieldExclusions.setToolTipText(Constant.TOOLTIP_EXCLUSION_FILE);
        this.textAreaExclusionsList.setToolTipText(Constant.TOOLTIP_EXCLUSION);
        this.textAreaFeatures.setToolTipText(Constant.TOOLTIP_FEATURES);
    }

    private IConvalidatoreValore createFieldValidator(final String field, final String message) {
        return new ConvalidatoreValoreAstratto(field) {
            @Override
            public List convalida(Object o) {
                String name = (String) o;
                List<String> errors = new ArrayList<String>();
                if (name.equals("")) {
                    errors.add("The data value " + message + " can not be empty");
                } else if (!name.endsWith(".txt")) {
                    errors.add("The File for data value " + message + " is not valid (.txt required)");
                }else {
                    if (!new File(name).isFile()) {
                        errors.add("The data value " + message + " is not an existing file");
                    }
                }
                return errors;
            }

            @Override
            public Object converti(Object o) {
                return o;
            }
        };
    }

    @Override
    public void visualizza() {
        FinestraDiDialogoPing dialog2 = (FinestraDiDialogoPing) this.vista.getSottoVista(ProjectWizardStep2.class.getName());
        this.setLocation(dialog2.getLocation());
        super.visualizza();
    }

    public void visualizzaBack() {
        FinestraDiDialogoPing dialog4 = (FinestraDiDialogoPing) this.vista.getSottoVista(ProjectWizardStep4.class.getName());
        this.setLocation(dialog4.getLocation());
        super.visualizza();
    }

    public void cleanExclusionElement() {
        this.labelExclusionsFile.setEnabled(false);
        this.buttonFileExclusions.setEnabled(false);
        this.radioButtonExclusions.setSelected(false);
        this.fieldExclusions.setEnabled(false);
        this.textAreaExclusionsList.setEnabled(true);
        this.labelExclusionsList.setEnabled(true);
        this.textAreaExclusionsList.setText(null);
        this.textAreaFeatures.setText(this.standardFeatures);
        createForm();

    }

    public void redisplayExclusionElement() {
        if (this.radioButtonExclusions.isSelected()) {
            this.labelExclusionsFile.setEnabled(true);
            this.buttonFileExclusions.setEnabled(true);
            this.fieldExclusions.setEnabled(true);
            this.textAreaExclusionsList.setEnabled(false);
            this.labelExclusionsList.setEnabled(false);
            createForm();
        } else {
            this.labelExclusionsFile.setEnabled(false);
            this.buttonFileExclusions.setEnabled(false);
            this.fieldExclusions.setEnabled(false);
            this.textAreaExclusionsList.setEnabled(true);
            this.labelExclusionsList.setEnabled(true);
            createForm();
        }
    }

    private void loadFeatures() {
        String features = PropertiesLoader.loadStandardFeatures();
        if (!features.equals("")) {
            this.standardFeatures = features.replace(",", "\n") + "\n";
        }
        this.textAreaFeatures.setText(this.standardFeatures);
    }
}
